### ISSUE TITLE
What does `long: true` do?

### ISSUE THREAD

**Issue by christianbundy** [dominictarr/multiblob#10]
I saw something like `blobs.ls({live: true, long: true})` in the tests, but I'm unfamiliar with `long`.

**Comment by dominictarr** [comment]
it does the same thing as `ls -l`
from `man ls`
`       -l     use a long listing format`
basically it includes all the metadata.

**Comment by christianbundy** [comment]
@dominictarr Thanks! I didn't make the connection.
